### ISSUE TITLE
WOTLK Bug (sometimes) when Click on name tab

### ISSUE THREAD

**Issue by Jorvanus** [Legacy-of-Sylvanaar/wow-instant-messenger#32] opened 2023-01-26 05:38 UTC
Not always something that happens, but this pops up and I can't click back into the message tab. 

12x WIM/Sources/TabHandler.lua:486: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: WIM3_msgFrame4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@WIM/Sources/TabHandler.lua"]:486: in function `JumpToTab'
[string "@WIM/Sources/TabHandler.lua"]:332: in function <WIM/Sources/TabHandler.lua:327>

Locals:
(*temporary) = WIM3_msgFrame4 {
 0 = <userdata>
 fadeOut = <function> defined @WIM/Sources/WindowHandler.lua:860
 isOnHyperLink = false
 lastDate = "01/26/2023"
 class = "Shaman"
 isNew = false
 offScreen = 0
 isParent = true
 msgSent = false
 level = 80
 Hide = <function> defined @WIM/Sources/WindowHandler.lua:1255
 fadedIn = true
 Hide_Normal = <function> defined =[C]:-1
 animation = <table> {
 }
 Pop = <function> defined @WIM/Sources/WindowHandler.lua:1138
 isWimWindow = true
 age = 494714.304000
 msgWaiting = false
 delayFade = false
 delayFadeElapsed = 0
 classColor = "2459FF"
 SendWho = <function> defined @WIM/Sources/WindowHandler.lua:1023
 SafeGetTop = <function> defined @WIM/Sources/WindowHandler.lua:1303
 AddMessageRaw = <function> defined @WIM/Sources/WindowHandler.lua:931
 AddMessage = <function> defined @WIM/Sources/WindowHandler.lua:924
 helperFrame = WIM_WindowHelperFrame {
 }
 SafeGetRight = <function> defined @WIM/Sources/WindowHandler.lua:1300
 UpdateIcon = <function> defined @WIM/Sources/WindowHandler.lua:946
 guild = "Double Entendre"
 animators = <table> {
 }
 customSize = true
 WhoCallback = <function> defined @WIM/Sources/WindowHandler.lua:1011
 SetScale_Orig = <function> defined =[C]:-1
 GetRuleSet = <function> defined @WIM/Sources/WindowHandler.lua:1128
 isMoving = false
 race = "Orc"
 lastActivity = 494892.786000
 theUser = "Daryi"
 fadeElapsed = 0
 AddEventMessage = <function> defined @WIM/Sources/WindowHandler.lua:935
 unreadCount = 0
 bn = <table> {
 }
 initialized = true
 type = "whisper"
 UpdateCharDetails = <function> defined @WIM/Sources/WindowHandler.lua:1007
 tabStrip = WIM_TabStrip1 {
 }
 hasMoved = true
 SafeGetLeft = <function> defined @WIM/Sources/WindowHandler.lua:1297
 isHistory = true
 widgets = <table> {
 }
 SafeGetBottom = <function> defined @WIM/Sources/WindowHandler.lua:1306
 online = true
 UpdateProps = <function> defined @WIM/Sources/WindowHandler.lua:1203
 SetScale = <function> defined @WIM/Sources/WindowHandler.lua:818
 location = "Orgrimmar"
 fadeIn = <function> defined @WIM/Sources/WindowHandler.lua:859
 ResetAnimation = <function> defined @WIM/Sources/WindowHandler.lua:1283
}
(*temporary) = "TOPLEFT"
(*temporary) = WIM_UIParent {
 0 = <userdata>
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = 1428.656006
(*temporary) = 665.250122

**Comment by biacz** [comment] 2023-01-27 11:48
same here

**Comment by Pazza** [comment] 2023-01-27 23:05
Duplicate of #11

**Closed by Pazza** 2023-01-27 23:05 UTC
Labels: duplicate
