### ISSUE TITLE
if there is a message which is filtered.. and there stays view message.. i cant click it.. so i need to tell the ppl to write it other so i can read it... thats kinda annoying

### ISSUE THREAD

**Issue by Turett** [Legacy-of-Sylvanaar/wow-instant-messenger#68] opened 2024-02-18 00:37 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pazza** [comment] 2024-02-19 20:56
I am aware of this issue. I need to review possible solutions. Thank you for your patience.

**Comment by dartraiden** [comment] 2024-03-10 22:34
Duplicate of https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/issues/49

**Comment by Pazza** [comment] 2024-05-24 22:59
I just posted an update. I added a workaround for this. implementing the same behavior as the default UI is too complicated so WIM will ignore these messages and deliver them directly to the default chat frame instead.

**Comment by Pazza** [comment] 2024-06-11 22:24
I posted a beta on curse which is a rewrite of all the chat events including support for censored messages. Let me know if everything is working please.

**Comment by Pazza** [comment] 2024-06-13 17:13
These changes are now live.

**Closed by Pazza** 2024-06-13 17:13 UTC
