### ISSUE TITLE
Small bug and small feature, but great update for Season of Discovery

### ISSUE THREAD

**Issue by eusi** [Legacy-of-Sylvanaar/wow-instant-messenger#69] opened 2024-02-19 07:54 UTC
1. "Click to update..." does not show the location after you have clicked (however "/who player" works reliably in general)
![2024-02-19 08_43_57-Window](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/assets/5718902/649764dc-eae4-40d7-b6d9-c3101d6e27a9)

2. On the same dialog if you do a right-click you should see the link of warcraftlogs for vanilla in addition for SoD.
- Regular one:
https://www.warcraftlogs.com/character/XX/SERVER/PLAYER
- SoD one:
https://vanilla.warcraftlogs.com/character/XX/SERVER/PLAYER

(XX stands for eu, us etc)

Thanks!

P.S. I am not sure if some of the other links could be deleted, like WoWArmory etc (since does not exist any longer)

**Comment by eusi** [comment] 2024-02-19 14:16
I already started with a potential fix for my ticket (links are corrected), but I have one issue: who-command is not reliable?

On my fork, if I press on the button, it is doing a /who (you can see the yellow text with p.name, level, location etc. in the chat but the registered eventHandler (that should grab the infos and push it to the WIM frame) is never called... I don't know why, thought this should work. I mean, at least you see the yellow text in the chat now, but would be better to see the location in the WIM window (as expected).

My fork/branch: https://github.com/eusi/wow-instant-messenger/commit/3678a90f1fdae95baaffc2db29f2c660d0dbff1d

Maybe someone can help?

**Comment by eusi** [comment] 2024-02-20 13:30
> I should update the tooltip to remove the update location... WIM used to do who lookups to obtain this information, but Blizzard removed the ability for addons to do this, blocking the action, so it was removed. You can of course continue to do it manually. WIM will pull this information from wherever it can, party members, guild members, raid, etc. Outside of that, this feature is dead unfortunately.

Thanks for your reply!

Do you think my way via `_G.C_FriendList.SendWho("n-"..self.theUser)` and the registered eventHandlerWho() won't work to get the location? Am I doing something wrong there?

**Comment by Pazza** [comment] 2024-02-20 14:08
Does it work?

**Comment by eusi** [comment] 2024-03-04 07:37
@Pazza May I ask by when we can expect the following pull request to be merged (which fixes this issue) and a new version of the addon to be released?

https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/pull/70

Thanks

**Comment by Pazza** [comment] 2024-03-04 13:59
When I have a moment to review and test it.

**Comment by Pazza** [comment] 2024-03-04 21:07
I reviewed it and made a minor change. I added a second parameter to WIM's SendWho method to invoke blizzard's who lookup. The problem is that it was throwing a blocked error whenever a new window was opened. So now when initiated through shortcut, it explicitly requests the blizzard's who call to be invoked.

It isn't the most ideal solution but it works. The limitations are that if you have FriendsList open it will redirect the user to the who frame and then close it. And if it isn't open, you'll still hear the window close as it opens and closes very quickly. 

Honestly though, for this use case, I think it is OK.

Thank you for your contribution.

**Closed by Pazza** 2024-03-04 21:07 UTC
